"""NSE symbol → display company name mapping for UI."""

from __future__ import annotations

_NSE_NAMES: dict[str, str] = {
    "RELIANCE": "Reliance Industries Ltd.",
    "TCS": "Tata Consultancy Services",
    "HDFCBANK": "HDFC Bank Ltd.",
    "BHARTIARTL": "Bharti Airtel Ltd.",
    "ICICIBANK": "ICICI Bank Ltd.",
    "INFOSYS": "Infosys Ltd.",
    "INFY": "Infosys Ltd.",
    "SBIN": "State Bank of India",
    "LICI": "LIC of India",
    "HINDUNILVR": "Hindustan Unilever Ltd.",
    "ITC": "ITC Limited",
    "BAJFINANCE": "Bajaj Finance Ltd.",
    "BAJAJFINSV": "Bajaj Finserv Ltd.",
    "KOTAKBANK": "Kotak Mahindra Bank",
    "LT": "Larsen & Toubro Ltd.",
    "HCLTECH": "HCL Technologies Ltd.",
    "AXISBANK": "Axis Bank Ltd.",
    "ASIANPAINT": "Asian Paints Ltd.",
    "MARUTI": "Maruti Suzuki India",
    "SUNPHARMA": "Sun Pharmaceutical",
    "TATAMOTORS": "Tata Motors Ltd.",
    "TITAN": "Titan Company Ltd.",
    "WIPRO": "Wipro Ltd.",
    "ULTRACEMCO": "UltraTech Cement",
    "NESTLEIND": "Nestle India Ltd.",
    "POWERGRID": "Power Grid Corp.",
    "NTPC": "NTPC Ltd.",
    "ONGC": "Oil & Natural Gas Corp.",
    "ADANIENT": "Adani Enterprises",
    "ADANIPORTS": "Adani Ports & SEZ",
    "COALINDIA": "Coal India Ltd.",
    "TATASTEEL": "Tata Steel Ltd.",
    "JSWSTEEL": "JSW Steel Ltd.",
    "HINDALCO": "Hindalco Industries",
    "VEDL": "Vedanta Ltd.",
    "GRASIM": "Grasim Industries",
    "BRITANNIA": "Britannia Industries",
    "DIVISLAB": "Divi's Laboratories",
    "DRREDDY": "Dr. Reddy's Laboratories",
    "CIPLA": "Cipla Ltd.",
    "APOLLOHOSP": "Apollo Hospitals",
    "HDFCLIFE": "HDFC Life Insurance",
    "SBILIFE": "SBI Life Insurance",
    "TECHM": "Tech Mahindra Ltd.",
    "BAJAJ-AUTO": "Bajaj Auto Ltd.",
    "BAJAJAUTO": "Bajaj Auto Ltd.",
    "EICHERMOT": "Eicher Motors Ltd.",
    "HEROMOTOCO": "Hero MotoCorp Ltd.",
    "M&M": "Mahindra & Mahindra",
    "MM": "Mahindra & Mahindra",
    "TATACONSUM": "Tata Consumer Products",
    "BPCL": "Bharat Petroleum Corp.",
    "IOC": "Indian Oil Corp.",
    "HPCL": "Hindustan Petroleum",
    "GAIL": "GAIL (India) Ltd.",
    "INDUSINDBK": "IndusInd Bank Ltd.",
    "BANDHANBNK": "Bandhan Bank Ltd.",
    "FEDERALBNK": "Federal Bank Ltd.",
    "PNB": "Punjab National Bank",
    "BANKBARODA": "Bank of Baroda",
    "CANBK": "Canara Bank Ltd.",
    "UNIONBANK": "Union Bank of India",
    "IDFCFIRSTB": "IDFC First Bank",
    "YESBANK": "Yes Bank Ltd.",
    "RBLBANK": "RBL Bank Ltd.",
    "KARURVYSYA": "Karur Vysya Bank",
    "SHRIRAMFIN": "Shriram Finance Ltd.",
    "JIOFIN": "Jio Financial Services",
    "BAJAJHFL": "Bajaj Housing Finance",
    "LICHSGFIN": "LIC Housing Finance",
    "PNBHOUSING": "PNB Housing Finance",
    "CANFINHOME": "Can Fin Homes Ltd.",
    "RECLTD": "REC Limited",
    "PFC": "Power Finance Corp.",
    "IRFC": "Indian Railway Finance",
    "MUTHOOTFIN": "Muthoot Finance Ltd.",
    "MANAPPURAM": "Manappuram Finance",
    "CHOLAFIN": "Cholamandalam Finance",
    "ABCAPITAL": "Aditya Birla Capital",
    "ANGELONE": "Angel One Ltd.",
    "MOTILALOFS": "Motilal Oswal Fin.",
    "ICICIGI": "ICICI Lombard General",
    "NIACL": "New India Assurance",
    "STARHEALTH": "Star Health Insurance",
    "MAXHEALTH": "Max Healthcare",
    "FORTIS": "Fortis Healthcare",
    "NHPC": "NHPC Ltd.",
    "TATAPOWER": "Tata Power Co. Ltd.",
    "TORNTPOWER": "Torrent Power Ltd.",
    "CESC": "CESC Limited",
    "JSL": "Jindal Stainless Ltd.",
    "HINDCOPPER": "Hindustan Copper",
    "NMDC": "NMDC Ltd.",
    "SAIL": "Steel Authority of India",
    "NATIONALUM": "National Aluminium",
    "NAUKRI": "Info Edge (India)",
    "ZOMATO": "Zomato Ltd.",
    "PAYTM": "One 97 Communications",
    "NYKAA": "FSN E-Commerce (Nykaa)",
    "DELHIVERY": "Delhivery Ltd.",
    "POLICYBZR": "PB Fintech Ltd.",
    "CARTRADE": "CarTrade Tech Ltd.",
    "INDIGO": "InterGlobe Aviation",
    "IRCTC": "Indian Railway Catering",
    "CONCOR": "Container Corp. of India",
    "BLUEDART": "Blue Dart Express",
    "VRL": "VRL Logistics Ltd.",
    "TCI": "TCI Ltd.",
    "MCDOWELL-N": "United Spirits Ltd.",
    "UBL": "United Breweries Ltd.",
    "JUBLFOOD": "Jubilant FoodWorks",
    "DEVYANI": "Devyani International",
    "WESTLIFE": "Westlife Foodworld",
    "SAPPHIRE": "Sapphire Foods India",
    "TRENT": "Trent Ltd.",
    "DMART": "Avenue Supermarts",
    "VMART": "V-Mart Retail Ltd.",
    "SHOPERSTOP": "Shoppers Stop Ltd.",
    "RAYMOND": "Raymond Ltd.",
    "ABFRL": "ABFRL (Aditya Birla Fashion)",
    "KPRMILL": "KPR Mill Ltd.",
    "PAGEIND": "Page Industries Ltd.",
    "MPHASIS": "Mphasis Ltd.",
    "LTIM": "LTIMindtree Ltd.",
    "LTIMINDTREE": "LTIMindtree Ltd.",
    "PERSISTENT": "Persistent Systems",
    "COFORGE": "Coforge Ltd.",
    "KPITTECH": "KPIT Technologies",
    "ZENSAR": "Zensar Technologies",
    "HEXAWARE": "Hexaware Technologies",
    "OFSS": "Oracle Financial Services",
    "INFOEDGE": "Info Edge (India)",
    "TMPV": "Tata Motors Passenger Vehicles",
    "TATAELXSI": "Tata Elxsi Ltd.",
    "DIXON": "Dixon Technologies",
    "AMBER": "Amber Enterprises",
    "VOLTAS": "Voltas Ltd.",
    "WHIRLPOOL": "Whirlpool of India",
    "BLUESTAR": "Blue Star Ltd.",
    "CROMPTON": "Crompton Greaves Consumer",
    "HAVELLS": "Havells India Ltd.",
    "POLYCAB": "Polycab India Ltd.",
    "KEI": "KEI Industries Ltd.",
    "ABB": "ABB India Ltd.",
    "SIEMENS": "Siemens Ltd.",
    "HONAUT": "Honeywell Automation",
    "BEL": "Bharat Electronics Ltd.",
    "HAL": "Hindustan Aeronautics",
    "BHEL": "Bharat Heavy Electricals",
    "BEML": "BEML Ltd.",
    "IRCON": "IRCON International",
    "NBCC": "NBCC (India) Ltd.",
    "SJVN": "SJVN Ltd.",
    "BHPCL": "BHEL",
    "PGHH": "Procter & Gamble Hygiene",
    "COLPAL": "Colgate-Palmolive India",
    "DABUR": "Dabur India Ltd.",
    "MARICO": "Marico Ltd.",
    "GODREJCP": "Godrej Consumer Products",
    "GODREJIND": "Godrej Industries Ltd.",
    "EMAMILTD": "Emami Ltd.",
    "JYOTHYLAB": "Jyothy Labs Ltd.",
    "PIDILITIND": "Pidilite Industries",
    "BERGER": "Berger Paints India",
    "KANSAINER": "Kansai Nerolac Paints",
    "AKZOINDIA": "Akzo Nobel India",
    "SRF": "SRF Ltd.",
    "DEEPAKNITR": "Deepak Nitrite Ltd.",
    "NAVINFLUOR": "Navin Fluorine Intl.",
    "VINATIORGA": "Vinati Organics Ltd.",
    "BALCHEMI": "Balaji Amines Ltd.",
    "AAPL": "Apple Inc.",  # US stocks fallback
}


def get_company_name(symbol: str) -> str:
    """Return display-friendly company name for a given NSE symbol."""
    clean = symbol.replace(".NS", "").replace(".BO", "").upper()
    return _NSE_NAMES.get(clean, clean.replace("-", " ").title())
